// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    ping_pong
    (
        init => init
        upgrade => upgrade
        ping => ping
        pong => pong
        open_contract => open_contract
        close_contract => close_contract
        set_deadline_and_activation_timestamp => set_deadline_and_activation_timestamp
        set_max_ping_amount => set_max_ping_amount
        set_max_funds => set_max_funds
        isOpen => is_open
        getMaxPingAmount => max_ping_amount
        getPingAmount => ping_amount
        getDeadline => deadline
        getActivationTimestamp => activation_timestamp
        getMaxFunds => max_funds
        getAllUsers => all_users
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
